//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFrameworkConsole.SCAccountWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SCAccountWS.AccountServiceSoap")]
    public interface AccountServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/findUser", ReplyAction="*")]
        NetFrameworkConsole.SCAccountWS.findUserResponse findUser(NetFrameworkConsole.SCAccountWS.findUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/findUser", ReplyAction="*")]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.findUserResponse> findUserAsync(NetFrameworkConsole.SCAccountWS.findUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 queryUsersResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/queryUsers", ReplyAction="*")]
        NetFrameworkConsole.SCAccountWS.queryUsersResponse queryUsers(NetFrameworkConsole.SCAccountWS.queryUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/queryUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.queryUsersResponse> queryUsersAsync(NetFrameworkConsole.SCAccountWS.queryUsersRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userInfos 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyUserInfo", ReplyAction="*")]
        NetFrameworkConsole.SCAccountWS.modifyUserInfoResponse modifyUserInfo(NetFrameworkConsole.SCAccountWS.modifyUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modifyUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.modifyUserInfoResponse> modifyUserInfoAsync(NetFrameworkConsole.SCAccountWS.modifyUserInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userIDs 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delUser", ReplyAction="*")]
        NetFrameworkConsole.SCAccountWS.delUserResponse delUser(NetFrameworkConsole.SCAccountWS.delUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delUser", ReplyAction="*")]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.delUserResponse> delUserAsync(NetFrameworkConsole.SCAccountWS.delUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 getUserAmountResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserAmount", ReplyAction="*")]
        NetFrameworkConsole.SCAccountWS.getUserAmountResponse getUserAmount(NetFrameworkConsole.SCAccountWS.getUserAmountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.getUserAmountResponse> getUserAmountAsync(NetFrameworkConsole.SCAccountWS.getUserAmountRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pageSize 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/queryUsersByPage", ReplyAction="*")]
        NetFrameworkConsole.SCAccountWS.queryUsersByPageResponse queryUsersByPage(NetFrameworkConsole.SCAccountWS.queryUsersByPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/queryUsersByPage", ReplyAction="*")]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.queryUsersByPageResponse> queryUsersByPageAsync(NetFrameworkConsole.SCAccountWS.queryUsersByPageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findUser", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.findUserRequestBody Body;
        
        public findUserRequest() {
        }
        
        public findUserRequest(NetFrameworkConsole.SCAccountWS.findUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class findUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        public findUserRequestBody() {
        }
        
        public findUserRequestBody(string userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.findUserResponseBody Body;
        
        public findUserResponse() {
        }
        
        public findUserResponse(NetFrameworkConsole.SCAccountWS.findUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class findUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string findUserResult;
        
        public findUserResponseBody() {
        }
        
        public findUserResponseBody(string findUserResult) {
            this.findUserResult = findUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryUsers", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.queryUsersRequestBody Body;
        
        public queryUsersRequest() {
        }
        
        public queryUsersRequest(NetFrameworkConsole.SCAccountWS.queryUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class queryUsersRequestBody {
        
        public queryUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.queryUsersResponseBody Body;
        
        public queryUsersResponse() {
        }
        
        public queryUsersResponse(NetFrameworkConsole.SCAccountWS.queryUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class queryUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string queryUsersResult;
        
        public queryUsersResponseBody() {
        }
        
        public queryUsersResponseBody(string queryUsersResult) {
            this.queryUsersResult = queryUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.modifyUserInfoRequestBody Body;
        
        public modifyUserInfoRequest() {
        }
        
        public modifyUserInfoRequest(NetFrameworkConsole.SCAccountWS.modifyUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modifyUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userInfos;
        
        public modifyUserInfoRequestBody() {
        }
        
        public modifyUserInfoRequestBody(string userInfos) {
            this.userInfos = userInfos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modifyUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modifyUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.modifyUserInfoResponseBody Body;
        
        public modifyUserInfoResponse() {
        }
        
        public modifyUserInfoResponse(NetFrameworkConsole.SCAccountWS.modifyUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modifyUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string modifyUserInfoResult;
        
        public modifyUserInfoResponseBody() {
        }
        
        public modifyUserInfoResponseBody(string modifyUserInfoResult) {
            this.modifyUserInfoResult = modifyUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delUser", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.delUserRequestBody Body;
        
        public delUserRequest() {
        }
        
        public delUserRequest(NetFrameworkConsole.SCAccountWS.delUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class delUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userIDs;
        
        public delUserRequestBody() {
        }
        
        public delUserRequestBody(string userIDs) {
            this.userIDs = userIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.delUserResponseBody Body;
        
        public delUserResponse() {
        }
        
        public delUserResponse(NetFrameworkConsole.SCAccountWS.delUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class delUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string delUserResult;
        
        public delUserResponseBody() {
        }
        
        public delUserResponseBody(string delUserResult) {
            this.delUserResult = delUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserAmountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserAmount", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.getUserAmountRequestBody Body;
        
        public getUserAmountRequest() {
        }
        
        public getUserAmountRequest(NetFrameworkConsole.SCAccountWS.getUserAmountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUserAmountRequestBody {
        
        public getUserAmountRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserAmountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserAmountResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.getUserAmountResponseBody Body;
        
        public getUserAmountResponse() {
        }
        
        public getUserAmountResponse(NetFrameworkConsole.SCAccountWS.getUserAmountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserAmountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserAmountResult;
        
        public getUserAmountResponseBody() {
        }
        
        public getUserAmountResponseBody(string getUserAmountResult) {
            this.getUserAmountResult = getUserAmountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUsersByPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryUsersByPage", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.queryUsersByPageRequestBody Body;
        
        public queryUsersByPageRequest() {
        }
        
        public queryUsersByPageRequest(NetFrameworkConsole.SCAccountWS.queryUsersByPageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class queryUsersByPageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pageNum;
        
        public queryUsersByPageRequestBody() {
        }
        
        public queryUsersByPageRequestBody(string pageSize, string pageNum) {
            this.pageSize = pageSize;
            this.pageNum = pageNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryUsersByPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryUsersByPageResponse", Namespace="http://tempuri.org/", Order=0)]
        public NetFrameworkConsole.SCAccountWS.queryUsersByPageResponseBody Body;
        
        public queryUsersByPageResponse() {
        }
        
        public queryUsersByPageResponse(NetFrameworkConsole.SCAccountWS.queryUsersByPageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class queryUsersByPageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string queryUsersByPageResult;
        
        public queryUsersByPageResponseBody() {
        }
        
        public queryUsersByPageResponseBody(string queryUsersByPageResult) {
            this.queryUsersByPageResult = queryUsersByPageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountServiceSoapChannel : NetFrameworkConsole.SCAccountWS.AccountServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceSoapClient : System.ServiceModel.ClientBase<NetFrameworkConsole.SCAccountWS.AccountServiceSoap>, NetFrameworkConsole.SCAccountWS.AccountServiceSoap {
        
        public AccountServiceSoapClient() {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetFrameworkConsole.SCAccountWS.findUserResponse NetFrameworkConsole.SCAccountWS.AccountServiceSoap.findUser(NetFrameworkConsole.SCAccountWS.findUserRequest request) {
            return base.Channel.findUser(request);
        }
        
        public string findUser(string userID) {
            NetFrameworkConsole.SCAccountWS.findUserRequest inValue = new NetFrameworkConsole.SCAccountWS.findUserRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.findUserRequestBody();
            inValue.Body.userID = userID;
            NetFrameworkConsole.SCAccountWS.findUserResponse retVal = ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).findUser(inValue);
            return retVal.Body.findUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.findUserResponse> NetFrameworkConsole.SCAccountWS.AccountServiceSoap.findUserAsync(NetFrameworkConsole.SCAccountWS.findUserRequest request) {
            return base.Channel.findUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.findUserResponse> findUserAsync(string userID) {
            NetFrameworkConsole.SCAccountWS.findUserRequest inValue = new NetFrameworkConsole.SCAccountWS.findUserRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.findUserRequestBody();
            inValue.Body.userID = userID;
            return ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).findUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetFrameworkConsole.SCAccountWS.queryUsersResponse NetFrameworkConsole.SCAccountWS.AccountServiceSoap.queryUsers(NetFrameworkConsole.SCAccountWS.queryUsersRequest request) {
            return base.Channel.queryUsers(request);
        }
        
        public string queryUsers() {
            NetFrameworkConsole.SCAccountWS.queryUsersRequest inValue = new NetFrameworkConsole.SCAccountWS.queryUsersRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.queryUsersRequestBody();
            NetFrameworkConsole.SCAccountWS.queryUsersResponse retVal = ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).queryUsers(inValue);
            return retVal.Body.queryUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.queryUsersResponse> NetFrameworkConsole.SCAccountWS.AccountServiceSoap.queryUsersAsync(NetFrameworkConsole.SCAccountWS.queryUsersRequest request) {
            return base.Channel.queryUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.queryUsersResponse> queryUsersAsync() {
            NetFrameworkConsole.SCAccountWS.queryUsersRequest inValue = new NetFrameworkConsole.SCAccountWS.queryUsersRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.queryUsersRequestBody();
            return ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).queryUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetFrameworkConsole.SCAccountWS.modifyUserInfoResponse NetFrameworkConsole.SCAccountWS.AccountServiceSoap.modifyUserInfo(NetFrameworkConsole.SCAccountWS.modifyUserInfoRequest request) {
            return base.Channel.modifyUserInfo(request);
        }
        
        public string modifyUserInfo(string userInfos) {
            NetFrameworkConsole.SCAccountWS.modifyUserInfoRequest inValue = new NetFrameworkConsole.SCAccountWS.modifyUserInfoRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.modifyUserInfoRequestBody();
            inValue.Body.userInfos = userInfos;
            NetFrameworkConsole.SCAccountWS.modifyUserInfoResponse retVal = ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).modifyUserInfo(inValue);
            return retVal.Body.modifyUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.modifyUserInfoResponse> NetFrameworkConsole.SCAccountWS.AccountServiceSoap.modifyUserInfoAsync(NetFrameworkConsole.SCAccountWS.modifyUserInfoRequest request) {
            return base.Channel.modifyUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.modifyUserInfoResponse> modifyUserInfoAsync(string userInfos) {
            NetFrameworkConsole.SCAccountWS.modifyUserInfoRequest inValue = new NetFrameworkConsole.SCAccountWS.modifyUserInfoRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.modifyUserInfoRequestBody();
            inValue.Body.userInfos = userInfos;
            return ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).modifyUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetFrameworkConsole.SCAccountWS.delUserResponse NetFrameworkConsole.SCAccountWS.AccountServiceSoap.delUser(NetFrameworkConsole.SCAccountWS.delUserRequest request) {
            return base.Channel.delUser(request);
        }
        
        public string delUser(string userIDs) {
            NetFrameworkConsole.SCAccountWS.delUserRequest inValue = new NetFrameworkConsole.SCAccountWS.delUserRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.delUserRequestBody();
            inValue.Body.userIDs = userIDs;
            NetFrameworkConsole.SCAccountWS.delUserResponse retVal = ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).delUser(inValue);
            return retVal.Body.delUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.delUserResponse> NetFrameworkConsole.SCAccountWS.AccountServiceSoap.delUserAsync(NetFrameworkConsole.SCAccountWS.delUserRequest request) {
            return base.Channel.delUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.delUserResponse> delUserAsync(string userIDs) {
            NetFrameworkConsole.SCAccountWS.delUserRequest inValue = new NetFrameworkConsole.SCAccountWS.delUserRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.delUserRequestBody();
            inValue.Body.userIDs = userIDs;
            return ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).delUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetFrameworkConsole.SCAccountWS.getUserAmountResponse NetFrameworkConsole.SCAccountWS.AccountServiceSoap.getUserAmount(NetFrameworkConsole.SCAccountWS.getUserAmountRequest request) {
            return base.Channel.getUserAmount(request);
        }
        
        public string getUserAmount() {
            NetFrameworkConsole.SCAccountWS.getUserAmountRequest inValue = new NetFrameworkConsole.SCAccountWS.getUserAmountRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.getUserAmountRequestBody();
            NetFrameworkConsole.SCAccountWS.getUserAmountResponse retVal = ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).getUserAmount(inValue);
            return retVal.Body.getUserAmountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.getUserAmountResponse> NetFrameworkConsole.SCAccountWS.AccountServiceSoap.getUserAmountAsync(NetFrameworkConsole.SCAccountWS.getUserAmountRequest request) {
            return base.Channel.getUserAmountAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.getUserAmountResponse> getUserAmountAsync() {
            NetFrameworkConsole.SCAccountWS.getUserAmountRequest inValue = new NetFrameworkConsole.SCAccountWS.getUserAmountRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.getUserAmountRequestBody();
            return ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).getUserAmountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetFrameworkConsole.SCAccountWS.queryUsersByPageResponse NetFrameworkConsole.SCAccountWS.AccountServiceSoap.queryUsersByPage(NetFrameworkConsole.SCAccountWS.queryUsersByPageRequest request) {
            return base.Channel.queryUsersByPage(request);
        }
        
        public string queryUsersByPage(string pageSize, string pageNum) {
            NetFrameworkConsole.SCAccountWS.queryUsersByPageRequest inValue = new NetFrameworkConsole.SCAccountWS.queryUsersByPageRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.queryUsersByPageRequestBody();
            inValue.Body.pageSize = pageSize;
            inValue.Body.pageNum = pageNum;
            NetFrameworkConsole.SCAccountWS.queryUsersByPageResponse retVal = ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).queryUsersByPage(inValue);
            return retVal.Body.queryUsersByPageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.queryUsersByPageResponse> NetFrameworkConsole.SCAccountWS.AccountServiceSoap.queryUsersByPageAsync(NetFrameworkConsole.SCAccountWS.queryUsersByPageRequest request) {
            return base.Channel.queryUsersByPageAsync(request);
        }
        
        public System.Threading.Tasks.Task<NetFrameworkConsole.SCAccountWS.queryUsersByPageResponse> queryUsersByPageAsync(string pageSize, string pageNum) {
            NetFrameworkConsole.SCAccountWS.queryUsersByPageRequest inValue = new NetFrameworkConsole.SCAccountWS.queryUsersByPageRequest();
            inValue.Body = new NetFrameworkConsole.SCAccountWS.queryUsersByPageRequestBody();
            inValue.Body.pageSize = pageSize;
            inValue.Body.pageNum = pageNum;
            return ((NetFrameworkConsole.SCAccountWS.AccountServiceSoap)(this)).queryUsersByPageAsync(inValue);
        }
    }
}
