//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NwomWs
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.service.anlysis.plugins.inspur.com/", ConfigurationName="NwomWs.LteNwomWsServiceImpl")]
    public interface LteNwomWsServiceImpl
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NwomWs.excuteScheduleTaskResponse> excuteScheduleTaskAsync(NwomWs.excuteScheduleTask request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NwomWs.eomsAlarmWorksheetResponse> eomsAlarmWorksheetAsync(NwomWs.eomsAlarmWorksheet request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<NwomWs.tuomingAnlysisResponse> tuomingAnlysisAsync(NwomWs.tuomingAnlysis request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class excuteScheduleTask
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="excuteScheduleTask", Namespace="http://impl.service.anlysis.plugins.inspur.com/", Order=0)]
        public NwomWs.excuteScheduleTaskBody Body;
        
        public excuteScheduleTask()
        {
        }
        
        public excuteScheduleTask(NwomWs.excuteScheduleTaskBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class excuteScheduleTaskBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string scheduleObjId;
        
        public excuteScheduleTaskBody()
        {
        }
        
        public excuteScheduleTaskBody(string scheduleObjId)
        {
            this.scheduleObjId = scheduleObjId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class excuteScheduleTaskResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="excuteScheduleTaskResponse", Namespace="http://impl.service.anlysis.plugins.inspur.com/", Order=0)]
        public NwomWs.excuteScheduleTaskResponseBody Body;
        
        public excuteScheduleTaskResponse()
        {
        }
        
        public excuteScheduleTaskResponse(NwomWs.excuteScheduleTaskResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class excuteScheduleTaskResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public excuteScheduleTaskResponseBody()
        {
        }
        
        public excuteScheduleTaskResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eomsAlarmWorksheet
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eomsAlarmWorksheet", Namespace="http://impl.service.anlysis.plugins.inspur.com/", Order=0)]
        public NwomWs.eomsAlarmWorksheetBody Body;
        
        public eomsAlarmWorksheet()
        {
        }
        
        public eomsAlarmWorksheet(NwomWs.eomsAlarmWorksheetBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class eomsAlarmWorksheetBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public eomsAlarmWorksheetBody()
        {
        }
        
        public eomsAlarmWorksheetBody(string arg0, string arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eomsAlarmWorksheetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eomsAlarmWorksheetResponse", Namespace="http://impl.service.anlysis.plugins.inspur.com/", Order=0)]
        public NwomWs.eomsAlarmWorksheetResponseBody Body;
        
        public eomsAlarmWorksheetResponse()
        {
        }
        
        public eomsAlarmWorksheetResponse(NwomWs.eomsAlarmWorksheetResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class eomsAlarmWorksheetResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public eomsAlarmWorksheetResponseBody()
        {
        }
        
        public eomsAlarmWorksheetResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class tuomingAnlysis
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="tuomingAnlysis", Namespace="http://impl.service.anlysis.plugins.inspur.com/", Order=0)]
        public NwomWs.tuomingAnlysisBody Body;
        
        public tuomingAnlysis()
        {
        }
        
        public tuomingAnlysis(NwomWs.tuomingAnlysisBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class tuomingAnlysisBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public tuomingAnlysisBody()
        {
        }
        
        public tuomingAnlysisBody(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class tuomingAnlysisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="tuomingAnlysisResponse", Namespace="http://impl.service.anlysis.plugins.inspur.com/", Order=0)]
        public NwomWs.tuomingAnlysisResponseBody Body;
        
        public tuomingAnlysisResponse()
        {
        }
        
        public tuomingAnlysisResponse(NwomWs.tuomingAnlysisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class tuomingAnlysisResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public tuomingAnlysisResponseBody()
        {
        }
        
        public tuomingAnlysisResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface LteNwomWsServiceImplChannel : NwomWs.LteNwomWsServiceImpl, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class LteNwomWsServiceImplClient : System.ServiceModel.ClientBase<NwomWs.LteNwomWsServiceImpl>, NwomWs.LteNwomWsServiceImpl
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LteNwomWsServiceImplClient() : 
                base(LteNwomWsServiceImplClient.GetDefaultBinding(), LteNwomWsServiceImplClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.LteNwomWsServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LteNwomWsServiceImplClient(EndpointConfiguration endpointConfiguration) : 
                base(LteNwomWsServiceImplClient.GetBindingForEndpoint(endpointConfiguration), LteNwomWsServiceImplClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LteNwomWsServiceImplClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LteNwomWsServiceImplClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LteNwomWsServiceImplClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LteNwomWsServiceImplClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LteNwomWsServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NwomWs.excuteScheduleTaskResponse> NwomWs.LteNwomWsServiceImpl.excuteScheduleTaskAsync(NwomWs.excuteScheduleTask request)
        {
            return base.Channel.excuteScheduleTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<NwomWs.excuteScheduleTaskResponse> excuteScheduleTaskAsync(string scheduleObjId)
        {
            NwomWs.excuteScheduleTask inValue = new NwomWs.excuteScheduleTask();
            inValue.Body = new NwomWs.excuteScheduleTaskBody();
            inValue.Body.scheduleObjId = scheduleObjId;
            return ((NwomWs.LteNwomWsServiceImpl)(this)).excuteScheduleTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NwomWs.eomsAlarmWorksheetResponse> NwomWs.LteNwomWsServiceImpl.eomsAlarmWorksheetAsync(NwomWs.eomsAlarmWorksheet request)
        {
            return base.Channel.eomsAlarmWorksheetAsync(request);
        }
        
        public System.Threading.Tasks.Task<NwomWs.eomsAlarmWorksheetResponse> eomsAlarmWorksheetAsync(string arg0, string arg1, string arg2)
        {
            NwomWs.eomsAlarmWorksheet inValue = new NwomWs.eomsAlarmWorksheet();
            inValue.Body = new NwomWs.eomsAlarmWorksheetBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((NwomWs.LteNwomWsServiceImpl)(this)).eomsAlarmWorksheetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NwomWs.tuomingAnlysisResponse> NwomWs.LteNwomWsServiceImpl.tuomingAnlysisAsync(NwomWs.tuomingAnlysis request)
        {
            return base.Channel.tuomingAnlysisAsync(request);
        }
        
        public System.Threading.Tasks.Task<NwomWs.tuomingAnlysisResponse> tuomingAnlysisAsync(string arg0)
        {
            NwomWs.tuomingAnlysis inValue = new NwomWs.tuomingAnlysis();
            inValue.Body = new NwomWs.tuomingAnlysisBody();
            inValue.Body.arg0 = arg0;
            return ((NwomWs.LteNwomWsServiceImpl)(this)).tuomingAnlysisAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LteNwomWsServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LteNwomWsServiceImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.154.14.8/nwom/plugins/anlysis/ws/anlysis/LteNwomWsTask");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LteNwomWsServiceImplClient.GetBindingForEndpoint(EndpointConfiguration.LteNwomWsServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LteNwomWsServiceImplClient.GetEndpointAddress(EndpointConfiguration.LteNwomWsServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            LteNwomWsServiceImplPort,
        }
    }
}
